### PR TITLE
Changed import-image to correct AWS flag --disk-containers

### PR DESCRIPTION
**Pull request by minac**
AWS changed the import image command, so I changed import-image to correct AWS flag --disk-containers. http://docs.aws.amazon.com/cli/latest/reference/ec2/import-image.html

### CODE REVIEW

**Comment by dliappis** [comment]
@minac Actually I got a problem while testing this change:

```
Parameter validation failed:
Unknown parameter in DiskContainers[0]: "DiskContainers", must be one of: Description, Format, Url, UserBucket, DeviceName, SnapshotId
ERROR:root:awsAn error occured while execuring --regionAn error occured while execuring eu-west-1An error occured while execuring ec2An error occured while execuring import-imageAn error occured while execuring --disk-containers
```

This is with the latest versions of the aws libraries.

**Comment by minac** [comment]
Hey @dliappis I don't have the json I used in my shell history anymore, but the flag definitely changed to --disk-containers for this part. The problem you are having seems to be with the contents of the json, which may now be all mandatory, I guess. This is the shorthand that they say goes with this flag:
Description=string,Format=string,Url=string,UserBucket={S3Bucket=string,S3Key=string},DeviceName=string,SnapshotId=string

I would expect that with Description, Format and UserBucket you should be ok. No time to test right now I'm afraid. :(

**Comment by dliappis** [comment]
@minac Yes the dict that is passed right now to `--cli-input-json` in [here](https://github.com/dliappis/amiimporter/blob/master/amiimporter.py#L127-L136) so it has the `DiskContainers[]` list as key. Switching to the use of `--disk-containers` would require we restructure this dict as per the aws docs you mentioned.

The current code still works (using `--cli-input-json`) every time I have tried it locally, so this in not urgent.

**Comment by minac** [comment]
Perfect! If it works then no change is needed. It did not work for me, but
the problem could have been with the dict that I was using at the time.
Feel free to close this pull request.

Have a great day!

## 

Miguel
Website http://www.migueldavid.eu/ - LinkedIn
http://uk.linkedin.com/in/migueldavid/ - Taste Porto
http://www.tasteportofoodtours.com/

On 18 November 2016 at 10:41:45, Dimitrios Liappis (notifications@github.com)
wrote:

@minac https://github.com/minac Yes the dict that is passed right now to
--cli-input-json is this
https://github.com/dliappis/amiimporter/blob/master/amiimporter.py#L127-L136
so it has the DiskContainers[] list as key. Switching to the use of
--disk-containers would require we restructure this dict as per the aws
docs you mentioned.

The current code still works (using --cli-input-json) every time I have
tried it locally, so this in not urgent.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/dliappis/amiimporter/pull/2#issuecomment-261501826,
or mute
the thread

**Comment by minac** [comment]
This is likely no longer maintained, closing.

**Pull request closed without merging**
